DATABASE_USERNAME: "root"
DATABASE_PASSWORD: "123456"
DEVELOPMENT: "restaurant46"
DEVELOPMENT_HOST: "localhost:3000"
EMAIL_USERNAME: "tc45.jaxtina@gmail.com"
EMAIL_PASSWORD: "jaxtina45"
GOOGLE_APP_ID: "299200364671-naoloove34vq3h0uobn170l5c6hhnc91.apps.googleusercontent.com"
GOOGLE_APP_SECRET: "P1efCRpx1enpAkZg3cl_4SWO"
FACEBOOK_APP_ID: "420730465069349"
FACEBOOK_APP_SECRET: "da1f1f7ae897e6f73e719a5fa5175caf"
TWITTER_APP_ID: "iwPxCiFt1iujzz5ExXV48edY5"
TWITTER_APP_SECRET: "vQMBB0gpJaVTDFErYmpbIXa4dPalsPPqsl6bJwLL0Zka6xregJ"
