home:
  dish_popular_number: 8
  dish_lastest_number: 9
follow_link:
  facebook: "https://www.facebook.com/ngon.restaurants"
  google: "https://plus.google.com/+FoodyVn"
  twitter: "https://twitter.com/FoodyTV"
contact:
  max_length: 50
  subject:
    max_length: 255
  message:
    max_length: 255
paginate:
  table_perpage: 9
dish:
  image_size: [750, 380]
